# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'grpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngrpc.proto\"\x1e\n\x06\x61\x64\x64Msg\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x17\n\x08\x61\x64\x64Reply\x12\x0b\n\x03sum\x18\x01 \x01(\x05\"\x1a\n\x0brawImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"+\n\nimageReply\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"%\n\rdotProductMsg\x12\t\n\x01\x61\x18\x01 \x03(\x02\x12\t\n\x01\x62\x18\x02 \x03(\x02\"%\n\x0f\x64otProductReply\x12\x12\n\ndotproduct\x18\x01 \x01(\x02\"\x1b\n\x0cjsonImageMsg\x12\x0b\n\x03img\x18\x01 \x01(\t2,\n\x03\x61\x64\x64\x12%\n\raddTwoNumbers\x12\x07.addMsg\x1a\t.addReply\"\x00\x32\x37\n\x08rawImage\x12+\n\x0c\x63omputeImage\x12\x0c.rawImageMsg\x1a\x0b.imageReply\"\x00\x32\x45\n\ndotProduct\x12\x37\n\x11\x63omputeDotProduct\x12\x0e.dotProductMsg\x1a\x10.dotProductReply\"\x00\x32=\n\tjsonImage\x12\x30\n\x10\x63omputeJsonImage\x12\r.jsonImageMsg\x1a\x0b.imageReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDMSG']._serialized_start=14
  _globals['_ADDMSG']._serialized_end=44
  _globals['_ADDREPLY']._serialized_start=46
  _globals['_ADDREPLY']._serialized_end=69
  _globals['_RAWIMAGEMSG']._serialized_start=71
  _globals['_RAWIMAGEMSG']._serialized_end=97
  _globals['_IMAGEREPLY']._serialized_start=99
  _globals['_IMAGEREPLY']._serialized_end=142
  _globals['_DOTPRODUCTMSG']._serialized_start=144
  _globals['_DOTPRODUCTMSG']._serialized_end=181
  _globals['_DOTPRODUCTREPLY']._serialized_start=183
  _globals['_DOTPRODUCTREPLY']._serialized_end=220
  _globals['_JSONIMAGEMSG']._serialized_start=222
  _globals['_JSONIMAGEMSG']._serialized_end=249
  _globals['_ADD']._serialized_start=251
  _globals['_ADD']._serialized_end=295
  _globals['_RAWIMAGE']._serialized_start=297
  _globals['_RAWIMAGE']._serialized_end=352
  _globals['_DOTPRODUCT']._serialized_start=354
  _globals['_DOTPRODUCT']._serialized_end=423
  _globals['_JSONIMAGE']._serialized_start=425
  _globals['_JSONIMAGE']._serialized_end=486
# @@protoc_insertion_point(module_scope)
